#!/usr/bin/env bash
# this is a comment
echo $$ >> /var/run/holbertonscript.pid
trap "echo 'I hate the kill command'" SIGTERM  
trap "echo 'Y U no love me?!;
rm /var/run/holbertonscript.pid;exit'" SIGINT
trap 'rm /var/run/holbertonscript.pid;exit' SIGQUIT 
while true
do
    echo "To infinity and beyond"
    sleep 2
done
